### ISSUE TITLE
Timeline View not working 

### ISSUE THREAD

**Issue by SatoriDevil** [notion-enhancer/notion-enhancer#248]
**describe the bug**
The timeline view doesn't function for some reason, I couldn't find out why just yet but it looks bugged and it doesn't allow me to do anything in the view itself 

**expected behaviour**
I should be able to use the timeline view but for some reason it's not working 

**screenshots**
Default Notion
![image](https://user-images.githubusercontent.com/74328558/98871109-64a66500-2442-11eb-9dff-1e2b42154799.png)

Notion Enhancer 
![image](https://user-images.githubusercontent.com/74328558/98870910-037e9180-2442-11eb-9a27-65f7cb8d0cde.png)

**platform**
Windows 10  notion-enhancer/0.10.0 win32-x64 node-v12.16.2

**Comment by MrStanDu33** [comment]
Thank's for reporting, was thinking I was the only one to have this problem.

Seems to happen because of `theme.css`, see bellow

![image](https://user-images.githubusercontent.com/22714562/98873423-a81bc600-2478-11eb-930b-a4c5c8d15b00.png)

it's caused because of the `z-index: 1;` property of `theme.css` (in DevTools source pannel, it's located in `/core/css/theme.css`), see bellow

![image](https://user-images.githubusercontent.com/22714562/98873553-ec0ecb00-2478-11eb-90d0-89b9b1cbc9db.png)

disabling it solves the problem, see bellow

![image](https://user-images.githubusercontent.com/22714562/98873624-09dc3000-2479-11eb-94fd-c29ec5d46a0d.png)

I'm investigating why this line is here and how to prevent CSS leak without breaking anything else.

**Comment by MrStanDu33** [comment]
The bug seems to be fixed in [this commit](https://github.com/dragonwocky/notion-enhancer/commit/621aaa3978afd5cffa0540676c3a0378cc286185#diff-6335f2c56a3b7f12f0a2c2dd7cc271244f4d783dabd97802dd39f0d0a5bc3411L98-L100)

I think we'll have a fix soon, because this fix seems to be related with #211

**Comment by chigggsy** [comment]
Ahh yep. Been having this issue too. Glad it's not not just mine.

**Comment by dragonwocky** [comment]
should be fixed - colours aren't perfect in themes, but everything is visible/works.
