### ISSUE TITLE
Notion won't open

### ISSUE THREAD

**Issue by IslamSakrak** [notion-enhancer/notion-enhancer#358]
When closing notion and trying to open in notion won't open just at slight sec show it is loading than stops,
it doesn't run in the background since i checked the task manager

This is happening on Windows 10 Pro 64x 
what is the bug - what happens?

Won't open while I try with run as administrator, doesn't open when i launch notion desktop app from browser

**Comment by dragonwocky** [comment]
what version of notion and what version of the enhancer do you have installed? have you tried reinstalling both?

**Comment by IslamSakrak** [comment]
I haven't tried reinstalling both but i have everything on latest version

**Comment by IslamSakrak** [comment]
I will try removing enhancer and check does it work after it is being removed, if yes il add it again if not Il remove notion to and reinstall both

**Comment by IslamSakrak** [comment]
I had to reinstall everything to make it work

**Comment by IslamSakrak** [comment]
well this isn't a fix...

**Comment by dragonwocky** [comment]
is it working now? if so, it's a fix.
sometimes if something has updated someone silently or if there's been a user error it will break. I'm working on a more reliable installation, but this bug report can't help anything: all it tells me is that things weren't working but now they are. if you can provide steps to reproduce the crashing app or find error logs etc. then I'll reopen because then I'll actually have something to fix.
