### ISSUE TITLE
Ability to resize the size of "tabs"

### ISSUE THREAD

**Issue by fourteen-1** [notion-enhancer/notion-enhancer#418]
**problem**

The size of the tabs are so big that it increases the overall space taken by the titlebar and along with the already relatively large in-built "top-bar" of notion, almost 20% of my small laptop screen is being occupied, decreasing my working space significantly in the process. 

**solution**

Ability to resize the size of the tabs in order to decrease/increase the overall size of the titlebar. 

there could be a slider within the enhancer that lets the user set a custom size of their liking for the tabs.

**cons**

none that comes to mind.

**alternatives**

no

does this need to be implemented by the enhancer? could an external service work better?
no

Additional notes: Please, please, consider implementing this. Tabs are an amazing feature, it helps navigating while working in notion better (i have multiple notion windows open almost all the time) and also helps keep my taskbar organized. But big tab size is causing me and my laptop's limited screen problems. There's plenty of people using notion on their laptops so this problem is probably present for a lot of people out there. 

Thank you for reading!

**Comment by dragonwocky** [comment]
themes can currently modify tab styling, but since the enhancer is being majorly updated internally at the moment most development on those has slowed/stopped temporarily. if you come and ask in the [discord](https://discord.gg/sFWPXtA) or follow the contributing/documentation pages you might be able to do this yourself, otherwise wait until the update.

can you please provide a screenshot though? on my laptop (which doesn't have a particularly big screen), it only takes up a very small area of the screen.
