### ISSUE TITLE
Error on Apply

### ISSUE THREAD

**Issue by dixonge** [notion-enhancer/notion-enhancer#420]
**describe the bug**

### ERROR ###
Error: Cannot copy '../shared/notion-intl' to a subdirectory of itself, '../shared/notion-intl'.
    at /usr/local/lib/node_modules/notion-enhancer/node_modules/fs-extra/lib/copy/copy.js:210:21
    at FSReqCallback.oncomplete (node:fs:187:23)
=== END OF LOG ===

**expected behaviour**

Unable to find 'notion-intl' anywhere so unable to troubleshoot

**screenshots**

**platform**
MacOS Big Sur (11.0.1)

**Comment by dragonwocky** [comment]
uninstall and reinstall notion. this error only occurs if you're using an outdated version of the app.

**Comment by dixonge** [comment]
what? Notion auto-updates. I have always had the latest version. It is currently 2.0.11.

But never mind. That is a horrible response and you've saved me having to deal with a developer who doesn't give a shit.

**Comment by dragonwocky** [comment]
@dixonge sorry, excuse me?

I responded based on past reports of the same error, where it was happening with 2.0.7 and updating past that fixed it. Not sure how that's a "horrible response".

And honestly? This project is done in my own free time for 0 reward. I make it and help people because I want to, not because I owe you anything. If you want professional service, pay me. Otherwise, I'll keep my responses short and quick if I think I know the solution because I have no reason to do anything else.
