### ISSUE TITLE
Installation on Arch Linux: cannot find /pkg/notion-enhancer/usr

### ISSUE THREAD

**Issue by hoelzlmanuel** [notion-enhancer/notion-enhancer#422]
**describe the bug**

I tried installing this via https://aur.archlinux.org/packages/notion-enhancer/ but I only get the following: 

```npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path /home/manuel/.cache/yay/notion-enhancer/pkg/notion-enhancer/usr
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/home/manuel/.cache/yay/notion-enhancer/pkg/notion-enhancer/usr'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/manuel/.cache/yay/notion-enhancer/src/npm-cache/_logs/2021-02-13T13_59_28_469Z-debug.log
==> FEIL: En feil oppstod i package().
    Avbryter...
error making: %!s(func() string=0x5640854d2e80)
```

I have installed https://aur.archlinux.org/packages/notion-app/

Is this a problem on my end, on the packaging in the AUR or of the notion-enhancer itself, and how can I fix this?

**platform**
arch linux

**Comment by saifeddin1** [comment]
I think because Notion is not out for Linux yet

**Comment by mflotynski** [comment]
@saifeddin1  Notion definitely works on Linux. The same goes for notion-enhancer. I use it myself on arch and on garuda (arch derivative) right now. The readme (main page) also mentions how to install it on the arch, manjaro (and other linux systems) 😉

@hoelzlmanuel It looks like the problem is on your side as I just installed it on my laptop and it works perfectly.
Try looking what is the content of the ` /home/manuel/.cache/yay/notion-enhancer/src/npm-cache/_logs/2021-02-13T13_59_28_469Z-debug.log` which is mentioned in the error you showed us:
```
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/manuel/.cache/yay/notion-enhancer/src/npm-cache/_logs/2021-02-13T13_59_28_469Z-debug.log
```

If you won't find a solution to your problem then you could also try installing using npm (similar to recommended steps on windows/ubuntu/mac). To do this you will need to first install nodejs e.g. by running:
`yay -S nodejs`
after that you should be able to install notion-enhancer by running:
`npm install -g notion-enhancer`
You will probably get an error about permissions so you will need to fix them and run `notion-enhancer apply`.
**Please keep in mind** that by doing the above steps you will **loose "automatic" updates when running `yay -Syu`** (or whatever you use for updates). You will need to update manually by running `npm install -g notion-enhancer`.

**Comment by saifeddin1** [comment]
@mflotynski Well, That's good news for me!
