### ISSUE TITLE
字体太小，怎么放大页面，而不是同时也放大侧边栏啊

### ISSUE THREAD

**Issue by weoutp** [notion-enhancer/notion-enhancer#430]
字体太小，怎么放大页面，而不是同时也放大侧边栏啊

**Comment by dragonwocky** [comment]
@weoutp relying on google translate for this:

1. create a text file that ends with `.css` instead of `.txt`, put this in it and change the number to the font size you like (default is 16px):
```css
:root {
  --theme--font_body-size: 20px;
}
```

2. turn on the custom inserts module in the enhancer menu and select the css file you created with the file picker.

for further or future support with something like this, come ask in the discord. it's not a bug or a feature request, it's needing help with how to use an existing feature.
