### ISSUE TITLE
tray has no icon + titlebar glitched out

### ISSUE THREAD

**Issue by Veriox** [notion-enhancer/notion-enhancer#559]
![image](https://user-images.githubusercontent.com/89074027/129713237-f89aee6b-16c5-4a90-8529-117e79fedf29.png)

**Comment by metalzero24** [comment]
Same problem here

**Comment by dragonwocky** [comment]
tray icon issue is the same as https://github.com/notion-enhancer/notion-repackaged/issues/13 - this may be fixed in the latest release of notion-repackaged? please let us know if it still isn't in that issue thread.

titlebar issue is being tracked here: https://github.com/notion-enhancer/notion-enhancer/issues/291
