### ISSUE TITLE
Vim-style keybinds?

### ISSUE THREAD

**Issue by lukamanitta** [notion-enhancer/notion-enhancer#641]
I'm not entirely sure how feasible this is, but I think vim keybindings would be a very beneficial feature. Many developers have tried and given up on Notion because of its lack of support for this, and would bring more users to both Notion / Notion Enhancer. 

An ideal solution would implement customisable keybindings, but I think an implementation of the default keybindings would be sufficient for most prospective users.

I'm not entirely familiar with the capabilities of the enhancer so I don't know how difficult this would be to implement. If anybody has ideas / a potential direction I would be happy to contribute in any way I can.

The only alternative method I can think of is syncing a list of markdown files to Notion, which seems far more complicated and something well outside the scope of the enhancer.

**Comment by dragonwocky** [comment]
This has been requested before, and it's still a no, for a couple of reasons: 

- custom keybinds aren't plausible as there's no way to hook into notion's keybinds. It may be possible to mimic the behaviour of some and disable notion's defaults, but this would be unreliable and would come with other problems.

- Notion is block-based and comes with a complex user interface that is not easily navigable via keyboard alone as-is, let alone Vim keybinds.

- I don't personally use or see the attraction of Vim, so unless someone is paying me I'm unwilling to even try this.

If you or another developer would like to attempt creating this on your own, by all means go ahead. Otherwise, the closest you'll get might be something like https://vimium.github.io/
